name: code check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest]
            php-versions: ['8.2']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: get php version
      run: php --version
      with:
          php-version: ${{ matrix.php-versions }}       

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      with:
          php-version: ${{ matrix.php-versions }}        

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: phpcs check
      run: composer phpcs
