name: code check

on:
  push:
    branches: [ "main", "developement" ]
  pull_request:
    branches: [ "main", "developement" ]
  workflow_call:

permissions: {}

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest]
            php-versions: ['8.1', '8.2']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, zip    

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: get php version
      run: php --version     

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress   

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Install PHP_CodeSniffer
      run: |
              curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
              php phpcs.phar --version

    - uses: tinovyatkin/action-php-codesniffer@v1
      with: 
        files: "**.php"
        phpcs_path: php phpcs.phar
        standard: 'PSR12'    

    - name: phpcs check
      run: php phpcs.phar --standard=PSR12 app/
